import _add from './add.svg';
import _advance from './advance.svg';
import _arroba from './arroba.svg';
import _bag from './bag.svg';
import _bagMoney from './bag-money.svg';
import _bagMoneyBlack from './bag-money-black.svg';
import _bagWhiteLineBlue from './bag-white-line-blue.svg';
import _bars from './bars.svg';
import _bell from './bell.svg';
import _bellAdd from './bell-add.svg';
import _bellBlock from './bell-block.svg';
import _block from './block.svg';
import _board from './board.svg';
import _box from './box.svg';
import _btnLess from './btn-less.svg';
import _btnMore from './btn-more.svg';
import _cache from './cache.svg';
import _cadeado from './cadeado.svg';
import _calendar from './calendar.svg';
import _calendarAdd from './calendar-add.svg';
import _cart from './cart.svg';
import _cellphone from './cellphone.svg';
import _chartArea from './chart-area.svg';
import _chartBars from './chart-bars.svg';
import _chartBoard from './chart-board.svg';
import _chartCamera from './chart-camera.svg';
import _chartCandles from './chart-candles.svg';
import _chartCompare from './chart-compare.svg';
import _chartFunction from './chart-function.svg';
import _chartLine from './chart-line.svg';
import _chartLine_1 from './chart-line_1.svg';
import _chartSave from './chart-save.svg';
import _chartUndo from './chart-undo.svg';
import _chat from './chat.svg';
import _chatDo from './chat-do.svg';
import _checkmark from './checkmark.svg';
import _checkmarkSelected from './checkmark-selected.svg';
import _circleDown from './circle-down.svg';
import _circleMore from './circle-more.svg';
import _clipboardChart from './clipboard-chart.svg';
import _clips from './clips.svg';
import _clock from './clock.svg';
import _close from './close.svg';
import _comment from './comment.svg';
import _commentStar from './comment-star.svg';
import _comments from './comments.svg';
import _compass from './compass.svg';
import _config from './config.svg';
import _console from './console.svg';
import _coupom from './coupom.svg';
import _diamondBlueDark from './diamond-blue-dark.svg';
import _diamondBlueGrey from './diamond-blue-grey.svg';
import _diamondBlueWhite from './diamond-blue-white.svg';
import _diamondSolidDark from './diamond-solid-dark.svg';
import _down from './down.svg';
import _drawArrow from './draw-arrow.svg';
import _drawCircle from './draw-circle.svg';
import _drawFibonacciArc from './draw-fibonacci-arc.svg';
import _drawFibonacciFan from './draw-fibonacci-fan.svg';
import _drawFibonacciRetracement from './draw-fibonacci-retracement.svg';
import _drawFibonacciTimezone from './draw-fibonacci-timezone.svg';
import _drawHorizontalArrow from './draw-horizontal-arrow.svg';
import _drawHorizontalLine from './draw-horizontal-line.svg';
import _drawHorizontalRange from './draw-horizontal-range.svg';
import _drawHorizontalRay from './draw-horizontal-ray.svg';
import _drawInfinity from './draw-infinity.svg';
import _drawPitchfork from './draw-pitchfork.svg';
import _drawRay from './draw-ray.svg';
import _drawRetangle from './draw-retangle.svg';
import _drawText from './draw-text.svg';
import _drawTrendChannel from './draw-trend-channel.svg';
import _drawTrendLine from './draw-trend-line.svg';
import _drawTriangle from './draw-triangle.svg';
import _drawVerticalLine from './draw-vertical-line.svg';
import _drawVerticalRange from './draw-vertical-range.svg';
import _emojiAirplane from './emoji-airplane.svg';
import _emojiBall from './emoji-ball.svg';
import _emojiClock from './emoji-clock.svg';
import _emojiFace from './emoji-face.svg';
import _emojiFlag from './emoji-flag.svg';
import _emojiFolha from './emoji-folha.svg';
import _emojiHamburger from './emoji-hamburger.svg';
import _emojiHearth from './emoji-hearth.svg';
import _emojiLamp from './emoji-lamp.svg';
import _emoticonAdd from './emoticon-add.svg';
import _externalLink from './external-link.svg';
import _filePeople from './file-people.svg';
import _folder from './folder.svg';
import _funnel from './funnel.svg';
import _grid from './grid.svg';
import _hammerBlueGray from './hammer-blue-gray.svg';
import _hammerBlueWhite from './hammer-blue-white.svg';
import _hammerWhiteBlue from './hammer-white-blue.svg';
import _hand from './hand.svg';
import _headphone from './headphone.svg';
import _heart from './heart.svg';
import _home from './home.svg';
import _icCentralAjuda from './ic-central-ajuda.svg';
import _icPause from './ic-pause.svg';
import _icPlay from './ic-play.svg';
import _icoCarteira from './ico-carteira.svg';
import _ideasEmptyStateFollowing from './ideas-empty-state-following.svg';
import _ideasEmptyStateMasterRequired from './ideas-empty-state-master-required.svg';
import _image from './image.svg';
import _lamp from './lamp.svg';
import _left from './left.svg';
import _link from './link.svg';
import _list from './list.svg';
import _marker from './marker.svg';
import _menu from './menu.svg';
import _microphone from './microphone.svg';
import _moderadorBlue from './moderador-blue.svg';
import _moderadorBlueDark from './moderador-blue-dark.svg';
import _moderadorBlueGrey from './moderador-blue-grey.svg';
import _moderadorBlueWhite from './moderador-blue-white.svg';
import _moderadorSolidDark from './moderador-solid-dark.svg';
import _money from './money.svg';
import _moneyCircle from './money-circle.svg';
import _moreOptions from './more-options.svg';
import _ok from './ok.svg';
import _paperPlane from './paper-plane.svg';
import _parcerias from './parcerias.svg';
import _photo from './photo.svg';
import _plantao from './plantao.svg';
import _play from './play.svg';
import _player from './player.svg';
import _playerBlock from './player-block.svg';
import _radar from './radar.svg';
import _reload from './reload.svg';
import _right from './right.svg';
import _search from './search.svg';
import _setDown from './set-down.svg';
import _share from './share.svg';
import _signOut from './sign-out.svg';
import _smallImportant from './small-important.svg';
import _smallSound from './small-sound.svg';
import _socialFacebook from './social-facebook.svg';
import _socialSet from './social-set.svg';
import _socialTwitter from './social-twitter.svg';
import _socialWhatsapp from './social-whatsapp.svg';
import _socialYoutube from './social-youtube.svg';
import _sortAmountDown from './sort-amount-down.svg';
import _star from './star.svg';
import _starBkgdWhite from './star-bkgd-white.svg';
import _starSolidDark from './star-solid-dark.svg';
import _starWhite from './star-white.svg';
import _starYellowBlue from './star-yellow-blue.svg';
import _starYellowGrey from './star-yellow-grey.svg';
import _starYellowWhite from './star-yellow-white.svg';
import _tcBlueDark from './tc-blue-dark.svg';
import _tcBlueGrey from './tc-blue-grey.svg';
import _tcBlueWhite from './tc-blue-white.svg';
import _tcIconsArrow from './tc-icons-arrow.svg';
import _tcIconsBack from './tc-icons-back.svg';
import _tcIconsBlog from './tc-icons-blog.svg';
import _tcIconsCalculator from './tc-icons-calculator.svg';
import _tcIconsCalendar from './tc-icons-calendar.svg';
import _tcIconsCheck from './tc-icons-check.svg';
import _tcIconsClessidre from './tc-icons-clessidre.svg';
import _tcIconsClose from './tc-icons-close.svg';
import _tcIconsComment from './tc-icons-comment.svg';
import _tcIconsCompany from './tc-icons-company.svg';
import _tcIconsCompareProposals from './tc-icons-compare-proposals.svg';
import _tcIconsDocument from './tc-icons-document.svg';
import _tcIconsDownload from './tc-icons-download.svg';
import _tcIconsEdit from './tc-icons-edit.svg';
import _tcIconsEquity from './tc-icons-equity.svg';
import _tcIconsEstate from './tc-icons-estate.svg';
import _tcIconsFilters from './tc-icons-filters.svg';
import _tcIconsFinancing from './tc-icons-financing.svg';
import _tcIconsHide from './tc-icons-hide.svg';
import _tcIconsHome from './tc-icons-home.svg';
import _tcIconsLock from './tc-icons-lock.svg';
import _tcIconsLocked from './tc-icons-locked.svg';
import _tcIconsLogOut from './tc-icons-log-out.svg';
import _tcIconsMaximize from './tc-icons-maximize.svg';
import _tcIconsMenu from './tc-icons-menu.svg';
import _tcIconsMore from './tc-icons-more.svg';
import _tcIconsNoEvents from './tc-icons-no-events.svg';
import _tcIconsNotification from './tc-icons-notification.svg';
import _tcIconsPen from './tc-icons-pen.svg';
import _tcIconsPlus from './tc-icons-plus.svg';
import _tcIconsProposalDetails from './tc-icons-proposal-details.svg';
import _tcIconsRevert from './tc-icons-revert.svg';
import _tcIconsSearch from './tc-icons-search.svg';
import _tcIconsSettings from './tc-icons-settings.svg';
import _tcIconsShare from './tc-icons-share.svg';
import _tcIconsShow from './tc-icons-show.svg';
import _tcIconsTools from './tc-icons-tools.svg';
import _tcIconsTradeIdeas from './tc-icons-trade-ideas.svg';
import _tcIconsTrash from './tc-icons-trash.svg';
import _tcIconsUser from './tc-icons-user.svg';
import _tcIconsWealth from './tc-icons-wealth.svg';
import _tcMatrix from './tc-matrix.svg';
import _tcSmallArrow from './tc-small-arrow.svg';
import _tcSmallBack from './tc-small-back.svg';
import _tcSmallCheck from './tc-small-check.svg';
import _tcSmallClessidre from './tc-small-clessidre.svg';
import _tcSmallClock from './tc-small-clock.svg';
import _tcSmallClose from './tc-small-close.svg';
import _tcSmallComment from './tc-small-comment.svg';
import _tcSmallCopy from './tc-small-copy.svg';
import _tcSmallDocument from './tc-small-document.svg';
import _tcSmallDownload from './tc-small-download.svg';
import _tcSmallInfo from './tc-small-info.svg';
import _tcSmallLock from './tc-small-lock.svg';
import _tcSmallPlus from './tc-small-plus.svg';
import _tcSmallRevert from './tc-small-revert.svg';
import _tcSmallSettings from './tc-small-settings.svg';
import _tcTextEditorAttach from './tc-text-editor-attach.svg';
import _tcTextEditorBold from './tc-text-editor-bold.svg';
import _tcTextEditorCenterAlign from './tc-text-editor-center-align.svg';
import _tcTextEditorImage from './tc-text-editor-image.svg';
import _tcTextEditorIndentLeft from './tc-text-editor-indent-left.svg';
import _tcTextEditorIndentRight from './tc-text-editor-indent-right.svg';
import _tcTextEditorItalic from './tc-text-editor-italic.svg';
import _tcTextEditorLeftAlign from './tc-text-editor-left-align.svg';
import _tcTextEditorLink from './tc-text-editor-link.svg';
import _tcTextEditorList01 from './tc-text-editor-list-01.svg';
import _tcTextEditorList02 from './tc-text-editor-list-02.svg';
import _tcTextEditorQuote from './tc-text-editor-quote.svg';
import _tcTextEditorRightAlign from './tc-text-editor-right-align.svg';
import _tcTextEditorStrikethrough from './tc-text-editor-strikethrough.svg';
import _tcTextEditorUnderline from './tc-text-editor-underline.svg';
import _tcnews from './tcnews.svg';
import _terminaTcschool from './termina-tcschool.svg';
import _terminal from './terminal.svg';
import _terminalCotacoes from './terminal-cotacoes.svg';
import _terminalCursos from './terminal-cursos.svg';
import _terminalEventos from './terminal-eventos.svg';
import _terminalLoja from './terminal-loja.svg';
import _terminalMaster from './terminal-master.svg';
import _terminalPlantao from './terminal-plantao.svg';
import _terminalPodcasts from './terminal-podcasts.svg';
import _terminalRelatorio from './terminal-relatorio.svg';
import _terminalTrad3 from './terminal-trad3.svg';
import _terminalTradeIdeas from './terminal-trade-ideas.svg';
import _terminalVideos from './terminal-videos.svg';
import _trad3 from './trad3.svg';
import _trash from './trash.svg';
import _trophy from './trophy.svg';
import _up from './up.svg';
import _userAdd from './user-add.svg';
import _zoom from './zoom.svg';
import _zoomOut from './zoom-out.svg';
export const add = _add;
export const advance = _advance;
export const arroba = _arroba;
export const bag = _bag;
export const bagMoney = _bagMoney;
export const bagMoneyBlack = _bagMoneyBlack;
export const bagWhiteLineBlue = _bagWhiteLineBlue;
export const bars = _bars;
export const bell = _bell;
export const bellAdd = _bellAdd;
export const bellBlock = _bellBlock;
export const block = _block;
export const board = _board;
export const box = _box;
export const btnLess = _btnLess;
export const btnMore = _btnMore;
export const cache = _cache;
export const cadeado = _cadeado;
export const calendar = _calendar;
export const calendarAdd = _calendarAdd;
export const cart = _cart;
export const cellphone = _cellphone;
export const chartArea = _chartArea;
export const chartBars = _chartBars;
export const chartBoard = _chartBoard;
export const chartCamera = _chartCamera;
export const chartCandles = _chartCandles;
export const chartCompare = _chartCompare;
export const chartFunction = _chartFunction;
export const chartLine = _chartLine;
export const chartLine_1 = _chartLine_1;
export const chartSave = _chartSave;
export const chartUndo = _chartUndo;
export const chat = _chat;
export const chatDo = _chatDo;
export const checkmark = _checkmark;
export const checkmarkSelected = _checkmarkSelected;
export const circleDown = _circleDown;
export const circleMore = _circleMore;
export const clipboardChart = _clipboardChart;
export const clips = _clips;
export const clock = _clock;
export const close = _close;
export const comment = _comment;
export const commentStar = _commentStar;
export const comments = _comments;
export const compass = _compass;
export const config = _config;
export const console = _console;
export const coupom = _coupom;
export const diamondBlueDark = _diamondBlueDark;
export const diamondBlueGrey = _diamondBlueGrey;
export const diamondBlueWhite = _diamondBlueWhite;
export const diamondSolidDark = _diamondSolidDark;
export const down = _down;
export const drawArrow = _drawArrow;
export const drawCircle = _drawCircle;
export const drawFibonacciArc = _drawFibonacciArc;
export const drawFibonacciFan = _drawFibonacciFan;
export const drawFibonacciRetracement = _drawFibonacciRetracement;
export const drawFibonacciTimezone = _drawFibonacciTimezone;
export const drawHorizontalArrow = _drawHorizontalArrow;
export const drawHorizontalLine = _drawHorizontalLine;
export const drawHorizontalRange = _drawHorizontalRange;
export const drawHorizontalRay = _drawHorizontalRay;
export const drawInfinity = _drawInfinity;
export const drawPitchfork = _drawPitchfork;
export const drawRay = _drawRay;
export const drawRetangle = _drawRetangle;
export const drawText = _drawText;
export const drawTrendChannel = _drawTrendChannel;
export const drawTrendLine = _drawTrendLine;
export const drawTriangle = _drawTriangle;
export const drawVerticalLine = _drawVerticalLine;
export const drawVerticalRange = _drawVerticalRange;
export const emojiAirplane = _emojiAirplane;
export const emojiBall = _emojiBall;
export const emojiClock = _emojiClock;
export const emojiFace = _emojiFace;
export const emojiFlag = _emojiFlag;
export const emojiFolha = _emojiFolha;
export const emojiHamburger = _emojiHamburger;
export const emojiHearth = _emojiHearth;
export const emojiLamp = _emojiLamp;
export const emoticonAdd = _emoticonAdd;
export const externalLink = _externalLink;
export const filePeople = _filePeople;
export const folder = _folder;
export const funnel = _funnel;
export const grid = _grid;
export const hammerBlueGray = _hammerBlueGray;
export const hammerBlueWhite = _hammerBlueWhite;
export const hammerWhiteBlue = _hammerWhiteBlue;
export const hand = _hand;
export const headphone = _headphone;
export const heart = _heart;
export const home = _home;
export const icCentralAjuda = _icCentralAjuda;
export const icPause = _icPause;
export const icPlay = _icPlay;
export const icoCarteira = _icoCarteira;
export const ideasEmptyStateFollowing = _ideasEmptyStateFollowing;
export const ideasEmptyStateMasterRequired = _ideasEmptyStateMasterRequired;
export const image = _image;
export const lamp = _lamp;
export const left = _left;
export const link = _link;
export const list = _list;
export const marker = _marker;
export const menu = _menu;
export const microphone = _microphone;
export const moderadorBlue = _moderadorBlue;
export const moderadorBlueDark = _moderadorBlueDark;
export const moderadorBlueGrey = _moderadorBlueGrey;
export const moderadorBlueWhite = _moderadorBlueWhite;
export const moderadorSolidDark = _moderadorSolidDark;
export const money = _money;
export const moneyCircle = _moneyCircle;
export const moreOptions = _moreOptions;
export const ok = _ok;
export const paperPlane = _paperPlane;
export const parcerias = _parcerias;
export const photo = _photo;
export const plantao = _plantao;
export const play = _play;
export const player = _player;
export const playerBlock = _playerBlock;
export const radar = _radar;
export const reload = _reload;
export const right = _right;
export const search = _search;
export const setDown = _setDown;
export const share = _share;
export const signOut = _signOut;
export const smallImportant = _smallImportant;
export const smallSound = _smallSound;
export const socialFacebook = _socialFacebook;
export const socialSet = _socialSet;
export const socialTwitter = _socialTwitter;
export const socialWhatsapp = _socialWhatsapp;
export const socialYoutube = _socialYoutube;
export const sortAmountDown = _sortAmountDown;
export const star = _star;
export const starBkgdWhite = _starBkgdWhite;
export const starSolidDark = _starSolidDark;
export const starWhite = _starWhite;
export const starYellowBlue = _starYellowBlue;
export const starYellowGrey = _starYellowGrey;
export const starYellowWhite = _starYellowWhite;
export const tcBlueDark = _tcBlueDark;
export const tcBlueGrey = _tcBlueGrey;
export const tcBlueWhite = _tcBlueWhite;
export const tcIconsArrow = _tcIconsArrow;
export const tcIconsBack = _tcIconsBack;
export const tcIconsBlog = _tcIconsBlog;
export const tcIconsCalculator = _tcIconsCalculator;
export const tcIconsCalendar = _tcIconsCalendar;
export const tcIconsCheck = _tcIconsCheck;
export const tcIconsClessidre = _tcIconsClessidre;
export const tcIconsClose = _tcIconsClose;
export const tcIconsComment = _tcIconsComment;
export const tcIconsCompany = _tcIconsCompany;
export const tcIconsCompareProposals = _tcIconsCompareProposals;
export const tcIconsDocument = _tcIconsDocument;
export const tcIconsDownload = _tcIconsDownload;
export const tcIconsEdit = _tcIconsEdit;
export const tcIconsEquity = _tcIconsEquity;
export const tcIconsEstate = _tcIconsEstate;
export const tcIconsFilters = _tcIconsFilters;
export const tcIconsFinancing = _tcIconsFinancing;
export const tcIconsHide = _tcIconsHide;
export const tcIconsHome = _tcIconsHome;
export const tcIconsLock = _tcIconsLock;
export const tcIconsLocked = _tcIconsLocked;
export const tcIconsLogOut = _tcIconsLogOut;
export const tcIconsMaximize = _tcIconsMaximize;
export const tcIconsMenu = _tcIconsMenu;
export const tcIconsMore = _tcIconsMore;
export const tcIconsNoEvents = _tcIconsNoEvents;
export const tcIconsNotification = _tcIconsNotification;
export const tcIconsPen = _tcIconsPen;
export const tcIconsPlus = _tcIconsPlus;
export const tcIconsProposalDetails = _tcIconsProposalDetails;
export const tcIconsRevert = _tcIconsRevert;
export const tcIconsSearch = _tcIconsSearch;
export const tcIconsSettings = _tcIconsSettings;
export const tcIconsShare = _tcIconsShare;
export const tcIconsShow = _tcIconsShow;
export const tcIconsTools = _tcIconsTools;
export const tcIconsTradeIdeas = _tcIconsTradeIdeas;
export const tcIconsTrash = _tcIconsTrash;
export const tcIconsUser = _tcIconsUser;
export const tcIconsWealth = _tcIconsWealth;
export const tcMatrix = _tcMatrix;
export const tcSmallArrow = _tcSmallArrow;
export const tcSmallBack = _tcSmallBack;
export const tcSmallCheck = _tcSmallCheck;
export const tcSmallClessidre = _tcSmallClessidre;
export const tcSmallClock = _tcSmallClock;
export const tcSmallClose = _tcSmallClose;
export const tcSmallComment = _tcSmallComment;
export const tcSmallCopy = _tcSmallCopy;
export const tcSmallDocument = _tcSmallDocument;
export const tcSmallDownload = _tcSmallDownload;
export const tcSmallInfo = _tcSmallInfo;
export const tcSmallLock = _tcSmallLock;
export const tcSmallPlus = _tcSmallPlus;
export const tcSmallRevert = _tcSmallRevert;
export const tcSmallSettings = _tcSmallSettings;
export const tcTextEditorAttach = _tcTextEditorAttach;
export const tcTextEditorBold = _tcTextEditorBold;
export const tcTextEditorCenterAlign = _tcTextEditorCenterAlign;
export const tcTextEditorImage = _tcTextEditorImage;
export const tcTextEditorIndentLeft = _tcTextEditorIndentLeft;
export const tcTextEditorIndentRight = _tcTextEditorIndentRight;
export const tcTextEditorItalic = _tcTextEditorItalic;
export const tcTextEditorLeftAlign = _tcTextEditorLeftAlign;
export const tcTextEditorLink = _tcTextEditorLink;
export const tcTextEditorList01 = _tcTextEditorList01;
export const tcTextEditorList02 = _tcTextEditorList02;
export const tcTextEditorQuote = _tcTextEditorQuote;
export const tcTextEditorRightAlign = _tcTextEditorRightAlign;
export const tcTextEditorStrikethrough = _tcTextEditorStrikethrough;
export const tcTextEditorUnderline = _tcTextEditorUnderline;
export const tcnews = _tcnews;
export const terminaTcschool = _terminaTcschool;
export const terminal = _terminal;
export const terminalCotacoes = _terminalCotacoes;
export const terminalCursos = _terminalCursos;
export const terminalEventos = _terminalEventos;
export const terminalLoja = _terminalLoja;
export const terminalMaster = _terminalMaster;
export const terminalPlantao = _terminalPlantao;
export const terminalPodcasts = _terminalPodcasts;
export const terminalRelatorio = _terminalRelatorio;
export const terminalTrad3 = _terminalTrad3;
export const terminalTradeIdeas = _terminalTradeIdeas;
export const terminalVideos = _terminalVideos;
export const trad3 = _trad3;
export const trash = _trash;
export const trophy = _trophy;
export const up = _up;
export const userAdd = _userAdd;
export const zoom = _zoom;
export const zoomOut = _zoomOut;
//# sourceMappingURL=index.js.map