import _alert from './alert.svg';
import _alertFill from './alert-fill.svg';
import _arrowAngleContract from './arrow-angle-contract.svg';
import _arrowAngleExpand from './arrow-angle-expand.svg';
import _arrowBack from './arrow-back.svg';
import _arrowBoxExternalLink from './arrow-box-external-link.svg';
import _arrowCircleLeft from './arrow-circle-left.svg';
import _arrowCircleRight from './arrow-circle-right.svg';
import _arrowExternalLink from './arrow-external-link.svg';
import _arrowLargeDown from './arrow-large-down.svg';
import _arrowLargeLeft from './arrow-large-left.svg';
import _arrowLargeRight from './arrow-large-right.svg';
import _arrowLargeUp from './arrow-large-up.svg';
import _arrowPageLeft from './arrow-page-left.svg';
import _arrowPageRight from './arrow-page-right.svg';
import _arrowSmallDown from './arrow-small-down.svg';
import _arrowSmallLeft from './arrow-small-left.svg';
import _arrowSmallRight from './arrow-small-right.svg';
import _arrowSmallUp from './arrow-small-up.svg';
import _atSign from './at-sign.svg';
import _award from './award.svg';
import _bag from './bag.svg';
import _blog from './blog.svg';
import _bookmark from './bookmark.svg';
import _buy from './buy.svg';
import _carteira from './carteira.svg';
import _calculator from './calculator.svg';
import _calendarAdd from './calendar-add.svg';
import _calendarNoEvents from './calendar-no-events.svg';
import _calendar from './calendar.svg';
import _cameraFill from './camera-fill.svg';
import _canais from './canais.svg';
import _cards from './cards.svg';
import _caret from './caret.svg';
import _cart from './cart.svg';
import _chartArea from './chart-area.svg';
import _chartBars from './chart-bars.svg';
import _chartBoard from './chart-board.svg';
import _chartCamera from './chart-camera.svg';
import _chartCandles from './chart-candles.svg';
import _chartCompare from './chart-compare.svg';
import _chartDo from './chart-do.svg';
import _chartFunction from './chart-function.svg';
import _chartLine from './chart-line.svg';
import _chartSave from './chart-save.svg';
import _chartUndo from './chart-undo.svg';
import _chart from './chart.svg';
import _chat from './chat.svg';
import _check from './check.svg';
import _circleMinus from './circle-minus.svg';
import _circlePlus from './circle-plus.svg';
import _clock from './clock.svg';
import _closeCircle from './close-circle.svg';
import _close from './close.svg';
import _cloudUploud from './cloud-upload.svg';
import _comment from './comment.svg';
import _company from './company.svg';
import _compareProposal from './compare-proposals.svg';
import _copy from './copy.svg';
import _creditCardBack from './credit-card-back.svg';
import _crosshair from './crosshair.svg';
import _cursos from './cursos.svg';
import _dashBTG from './dash-BTG.svg';
import _dashboard from './dashboard.svg';
import _diretorio from './diretorio.svg';
import _download from './download.svg';
import _drawArrow from './draw-arrow.svg';
import _drawCircle from './draw-circle.svg';
import _drawFibonacciRetracement from './draw-fibonacci-retracement.svg';
import _drawHorizontalArrow from './draw-horizontal-arrow.svg';
import _drawHorizontalLine from './draw-horizontal-line.svg';
import _drawHorizontalRange from './draw-horizontal-range.svg';
import _drawHorizontalRay from './draw-horizontal-ray.svg';
import _drawInfinity from './draw-infinity.svg';
import _drawMarker from './draw-marker.svg';
import _drawPitchfork from './draw-pitchfork.svg';
import _drawRay from './draw-ray.svg';
import _drawRetangle from './draw-retangle.svg';
import _drawText from './draw-text.svg';
import _drawTrendChannel from './draw-trend-channel.svg';
import _drawTrendLine from './draw-trend-line.svg';
import _drawTriangle from './draw-triangle.svg';
import _drawVerticalLine from './draw-vertical-line.svg';
import _drawVerticalRange from './draw-vertical-range.svg';
import _edit from './edit.svg';
import _edit2 from './edit-2.svg';
import _editAtSign from './edit-at-sign.svg';
import _editAttach from './edit-attach.svg';
import _editBold from './edit-bold.svg';
import _editCenterAlign from './edit-center-align.svg';
import _editImage from './edit-image.svg';
import _editIndentLeft from './edit-indent-left.svg';
import _editIndentRight from './edit-indent-right.svg';
import _editItalic from './edit-italic.svg';
import _editLeftAlign from './edit-left-align.svg';
import _editLink from './edit-link.svg';
import _editNumberList from './edit-number-list.svg';
import _editPointList from './edit-point-list.svg';
import _editQuoteMark from './edit-quote-mark.svg';
import _editRightAlign from './edit-right-align.svg';
import _editStrikethrough from './edit-strikethrough.svg';
import _editUnderline from './edit-underline.svg';
import _emojiAdd from './emoji-add.svg';
import _emojiSad from './emoji-sad.svg';
import _equity from './equity.svg';
import _fileDoc from './file-doc.svg';
import _fileEmpty from './file-empty.svg';
import _fileMp3 from './file-mp3.svg';
import _filePdf from './file-pdf.svg';
import _filePpt from './file-ppt.svg';
import _fileText from './file-text.svg';
import _fileXls from './file-xls.svg';
import _fileXml from './file-xml.svg';
import _filter from './filter.svg';
import _gift from './gift.svg';
import _gripHorizontalLine from './grip-horizontal-line.svg';
import _gripHorizontalPoint from './grip-horizontal-point.svg';
import _gripVerticalLine from './grip-vertical-line.svg';
import _gripVerticalPoint from './grip-vertical-point.svg';
import _headphone from './headphone.svg';
import _headphones from './headphones.svg';
import _help from './help.svg';
import _hide from './hide.svg';
import _home from './home.svg';
import _hourGlass from './hour-glass.svg';
import _ideasEmptyStateFollowing from './ideas-empty-state-following.svg';
import _ideasEmptyStateMasterRequired from './ideas-empty-state-master-required.svg';
import _imageFill from './image-fill.svg';
import _indicator from './indicator.svg';
import _influencers from './influencers.svg';
import _infoCircle from './info-circle.svg';
import _list from './list.svg';
import _loadingDefault from './loading-default.svg';
import _lock from './lock.svg';
import _locked from './locked.svg';
import _logOut from './log-out.svg';
import _logoBubblesDark from './logo-bubbles-dark.svg';
import _logoBubblesLight from './logo-bubbles-light.svg';
import _master from './master.svg';
import _matrix from './matrix.svg';
import _maximize from './maximize.svg';
import _megaphone from './megaphone.svg';
import _menu from './menu.svg';
import _minimize from './minimize.svg';
import _moneyBag from './money-bag.svg';
import _moneyBagFill from './money-bag-fill.svg';
import _moneyCoin from './money-coin.svg';
import _moneySign from './money-sign.svg';
import _moreOptionHorizontal from './more-options-horizontal.svg';
import _moreOptionVertical from './more-options-vertical.svg';
import _move from './move.svg';
import _mover from './mover.svg';
import _mute from './mute.svg';
import _notification from './notification.svg';
import _notificationFill from './notification-fill.svg';
import _patchCheck from './patch-check.svg';
import _paymentMastercard from './payment-mastercard.svg';
import _pen from './pen.svg';
import _percentage from './percentage.svg';
import _pin from './pin.svg';
import _plantao from './plantao.svg';
import _playCircle from './play-circle.svg';
import _plus from './plus.svg';
import _proposalDetails from './proposal-details.svg';
import _radio_mic from './radio-mic.svg';
import _ranking from './ranking.svg';
import _refresh from './refresh.svg';
import _refreshSlash from './refresh-slash.svg';
import _reports from './reports.svg';
import _revert from './revert.svg';
import _search from './search.svg';
import _selector from './selector.svg';
import _sell from './sell.svg';
import _send from './send.svg';
import _settings from './settings.svg';
import _share from './share.svg';
import _shield from './shield.svg';
import _shieldCheck from './shield-check.svg';
import _show from './show.svg';
import _sliders from './sliders.svg';
import _slidersVertical from './sliders-vertical.svg';
import _soundOn from './sound-on.svg';
import _speakerphone from './speakerphone.svg';
import _star from './star.svg';
import _store from './store.svg';
import _suitabilityTestDark from './suitability-test-dark.svg';
import _suitabilityTestResult from './suitability-test-result.svg';
import _suitabilityTest from './suitability-test.svg';
import _support from './support.svg';
import _tcOptions from './tc-options.svg';
import _tcSchool from './TC-school.svg';
import _thumbDown from './thumb-down.svg';
import _thumbUp from './thumb-up.svg';
import _timeEvent from './time-event.svg';
import _torneio from './torneio.svg';
import _toggleOff from './toggle-off.svg';
import _toggleOn from './toggle-on.svg';
import _tools from './tools.svg';
import _tradeIdeas from './trade-ideas.svg';
import _trash from './trash.svg';
import _upload from './upload.svg';
import _user from './user.svg';
import _userAdd from './user-add.svg';
import _userList from './user-list.svg';
import _users from './users.svg';
import _video from './video.svg';
import _voucher from './voucher.svg';
import _wealth from './wealth.svg';
export const alert = _alert;
export const alertFill = _alertFill;
export const arrowAngleContrac = _arrowAngleContract;
export const arrowAngleExpand = _arrowAngleExpand;
export const arrowBack = _arrowBack;
export const arrowBoxExternalLink = _arrowBoxExternalLink;
export const arrowCircleLeft = _arrowCircleLeft;
export const arrowCircleRight = _arrowCircleRight;
export const arrowExternalLink = _arrowExternalLink;
export const arrowLargeDown = _arrowLargeDown;
export const arrowLargeLeft = _arrowLargeLeft;
export const arrowLargeRight = _arrowLargeRight;
export const arrowLargeUp = _arrowLargeUp;
export const arrowPageLeft = _arrowPageLeft;
export const arrowPageRight = _arrowPageRight;
export const arrowSmallDown = _arrowSmallDown;
export const arrowSmallLeft = _arrowSmallLeft;
export const arrowSmallRight = _arrowSmallRight;
export const arrowSmallUp = _arrowSmallUp;
export const atSign = _atSign;
export const award = _award;
export const bag = _bag;
export const blog = _blog;
export const bookmark = _bookmark;
export const buy = _buy;
export const carteira = _carteira;
export const calculator = _calculator;
export const calendarAdd = _calendarAdd;
export const calendarNoEvents = _calendarNoEvents;
export const calendar = _calendar;
export const cameraFill = _cameraFill;
export const canais = _canais;
export const cards = _cards;
export const caret = _caret;
export const cart = _cart;
export const chartArea = _chartArea;
export const chartBars = _chartBars;
export const chartBoard = _chartBoard;
export const chartCamera = _chartCamera;
export const chartCandles = _chartCandles;
export const chartCompare = _chartCompare;
export const chartDo = _chartDo;
export const chartFunction = _chartFunction;
export const chartLine = _chartLine;
export const chartSave = _chartSave;
export const chartUndo = _chartUndo;
export const chart = _chart;
export const chat = _chat;
export const check = _check;
export const circleMinus = _circleMinus;
export const circlePlus = _circlePlus;
export const clock = _clock;
export const closeCircle = _closeCircle;
export const close = _close;
export const cloudUpload = _cloudUploud;
export const comment = _comment;
export const company = _company;
export const compareProposal = _compareProposal;
export const copy = _copy;
export const creditCardBack = _creditCardBack;
export const crosshair = _crosshair;
export const cursos = _cursos;
export const dashBTG = _dashBTG;
export const dashboard = _dashboard;
export const diretorio = _diretorio;
export const download = _download;
export const drawArrow = _drawArrow;
export const drawCircle = _drawCircle;
export const drawFibonacciRetracement = _drawFibonacciRetracement;
export const drawHorizontalArrow = _drawHorizontalArrow;
export const drawHorizontalLine = _drawHorizontalLine;
export const drawHorizontalRange = _drawHorizontalRange;
export const drawHorizontalRay = _drawHorizontalRay;
export const drawInfinity = _drawInfinity;
export const drawMarker = _drawMarker;
export const drawPitchfork = _drawPitchfork;
export const drawRay = _drawRay;
export const drawRetangle = _drawRetangle;
export const drawText = _drawText;
export const drawTrendChannel = _drawTrendChannel;
export const drawTrendLine = _drawTrendLine;
export const drawTriangle = _drawTriangle;
export const drawVerticalLine = _drawVerticalLine;
export const drawVerticalRange = _drawVerticalRange;
export const edit = _edit;
export const edit2 = _edit2;
export const editAtSign = _editAtSign;
export const editAttach = _editAttach;
export const editBold = _editBold;
export const editCenterAlign = _editCenterAlign;
export const editImage = _editImage;
export const editIndentLeft = _editIndentLeft;
export const editIndentRight = _editIndentRight;
export const editItalic = _editItalic;
export const editLeftAlign = _editLeftAlign;
export const editLink = _editLink;
export const editNumberList = _editNumberList;
export const editPointList = _editPointList;
export const editQuoteMark = _editQuoteMark;
export const editRightAlign = _editRightAlign;
export const editStrikethrough = _editStrikethrough;
export const editUnderline = _editUnderline;
export const emojiAdd = _emojiAdd;
export const emojiSad = _emojiSad;
export const equity = _equity;
export const fileDoc = _fileDoc;
export const fileEmpty = _fileEmpty;
export const fileMp3 = _fileMp3;
export const filePdf = _filePdf;
export const filePpt = _filePpt;
export const fileText = _fileText;
export const fileXls = _fileXls;
export const fileXml = _fileXml;
export const filter = _filter;
export const giftt = _gift;
export const gripHorizontalLine = _gripHorizontalLine;
export const gripHorizontalPoint = _gripHorizontalPoint;
export const gripVerticalLine = _gripVerticalLine;
export const gripVerticalPoint = _gripVerticalPoint;
export const headphone = _headphone;
export const headphones = _headphones;
export const help = _help;
export const hide = _hide;
export const home = _home;
export const hourGlass = _hourGlass;
export const ideasEmptyStateFollowing = _ideasEmptyStateFollowing;
export const ideasEmptyStateMasterRequired = _ideasEmptyStateMasterRequired;
export const imageFill = _imageFill;
export const indicator = _indicator;
export const influencers = _influencers;
export const infoCircle = _infoCircle;
export const list = _list;
export const loadingDefault = _loadingDefault;
export const lock = _lock;
export const locked = _locked;
export const logOut = _logOut;
export const logoBubblesDark = _logoBubblesDark;
export const logoBubblesLight = _logoBubblesLight;
export const master = _master;
export const matrix = _matrix;
export const maximize = _maximize;
export const megaphone = _megaphone;
export const menu = _menu;
export const minimize = _minimize;
export const moneyBag = _moneyBag;
export const moneyBagFill = _moneyBagFill;
export const moneyCoin = _moneyCoin;
export const moneySign = _moneySign;
export const moreOptionHorizontal = _moreOptionHorizontal;
export const moreOptionVertical = _moreOptionVertical;
export const move = _move;
export const mover = _mover;
export const mute = _mute;
export const notificationFill = _notificationFill;
export const notification = _notification;
export const patchCheck = _patchCheck;
export const paymentMastercard = _paymentMastercard;
export const pen = _pen;
export const percentage = _percentage;
export const pin = _pin;
export const plantao = _plantao;
export const playCircle = _playCircle;
export const plus = _plus;
export const proposalDetails = _proposalDetails;
export const radioMic = _radio_mic;
export const ranking = _ranking;
export const refresh = _refresh;
export const refreshSlash = _refreshSlash;
export const reports = _reports;
export const revert = _revert;
export const search = _search;
export const selector = _selector;
export const sell = _sell;
export const send = _send;
export const settings = _settings;
export const share = _share;
export const shieldCheck = _shieldCheck;
export const shield = _shield;
export const show = _show;
export const sliders = _sliders;
export const soundOn = _soundOn;
export const slidersVertical = _slidersVertical;
export const speakerphone = _speakerphone;
export const star = _star;
export const store = _store;
export const suitabilityTestDark = _suitabilityTestDark;
export const suitabilityTestResult = _suitabilityTestResult;
export const suitabilityTest = _suitabilityTest;
export const support = _support;
export const tcOptions = _tcOptions;
export const tcSchool = _tcSchool;
export const thumbDown = _thumbDown;
export const thumbUp = _thumbUp;
export const timeEvent = _timeEvent;
export const torneio = _torneio;
export const toggleOff = _toggleOff;
export const toggleOn = _toggleOn;
export const tools = _tools;
export const tradeIdeas = _tradeIdeas;
export const trash = _trash;
export const upload = _upload;
export const userAdd = _userAdd;
export const userList = _userList;
export const user = _user;
export const users = _users;
export const video = _video;
export const voucher = _voucher;
export const wealth = _wealth;
//# sourceMappingURL=index.js.map