import _TCSchool from './TC-school.svg';
export const TCSchool = _TCSchool;
import _alertFill from './alert-fill.svg';
export const alertFill = _alertFill;
import _alert from './alert.svg';
export const alert = _alert;
import _arrowAngleContract from './arrow-angle-contract.svg';
export const arrowAngleContract = _arrowAngleContract;
import _arrowAngleExpand from './arrow-angle-expand.svg';
export const arrowAngleExpand = _arrowAngleExpand;
import _arrowBack from './arrow-back.svg';
export const arrowBack = _arrowBack;
import _arrowBoxExternalLink from './arrow-box-external-link.svg';
export const arrowBoxExternalLink = _arrowBoxExternalLink;
import _arrowCircleLeft from './arrow-circle-left.svg';
export const arrowCircleLeft = _arrowCircleLeft;
import _arrowCircleRight from './arrow-circle-right.svg';
export const arrowCircleRight = _arrowCircleRight;
import _arrowExternalLink from './arrow-external-link.svg';
export const arrowExternalLink = _arrowExternalLink;
import _arrowLargeDown from './arrow-large-down.svg';
export const arrowLargeDown = _arrowLargeDown;
import _arrowLargeLeft from './arrow-large-left.svg';
export const arrowLargeLeft = _arrowLargeLeft;
import _arrowLargeRight from './arrow-large-right.svg';
export const arrowLargeRight = _arrowLargeRight;
import _arrowLargeUp from './arrow-large-up.svg';
export const arrowLargeUp = _arrowLargeUp;
import _arrowPageLeft from './arrow-page-left.svg';
export const arrowPageLeft = _arrowPageLeft;
import _arrowPageRight from './arrow-page-right.svg';
export const arrowPageRight = _arrowPageRight;
import _arrowSmallDown from './arrow-small-down.svg';
export const arrowSmallDown = _arrowSmallDown;
import _arrowSmallLeft from './arrow-small-left.svg';
export const arrowSmallLeft = _arrowSmallLeft;
import _arrowSmallRight from './arrow-small-right.svg';
export const arrowSmallRight = _arrowSmallRight;
import _arrowSmallUp from './arrow-small-up.svg';
export const arrowSmallUp = _arrowSmallUp;
import _atSign from './at-sign.svg';
export const atSign = _atSign;
import _award from './award.svg';
export const award = _award;
import _bag from './bag.svg';
export const bag = _bag;
import _blog from './blog.svg';
export const blog = _blog;
import _bookmark from './bookmark.svg';
export const bookmark = _bookmark;
import _buy from './buy.svg';
export const buy = _buy;
import _calculator from './calculator.svg';
export const calculator = _calculator;
import _calendarAdd from './calendar-add.svg';
export const calendarAdd = _calendarAdd;
import _calendarNoEvents from './calendar-no-events.svg';
export const calendarNoEvents = _calendarNoEvents;
import _calendar from './calendar.svg';
export const calendar = _calendar;
import _cameraFill from './camera-fill.svg';
export const cameraFill = _cameraFill;
import _canais from './canais.svg';
export const canais = _canais;
import _cards from './cards.svg';
export const cards = _cards;
import _caret from './caret.svg';
export const caret = _caret;
import _cart from './cart.svg';
export const cart = _cart;
import _carteira from './carteira.svg';
export const carteira = _carteira;
import _chartArea from './chart-area.svg';
export const chartArea = _chartArea;
import _chartBars from './chart-bars.svg';
export const chartBars = _chartBars;
import _chartBoard from './chart-board.svg';
export const chartBoard = _chartBoard;
import _chartCamera from './chart-camera.svg';
export const chartCamera = _chartCamera;
import _chartCandles from './chart-candles.svg';
export const chartCandles = _chartCandles;
import _chartCompare from './chart-compare.svg';
export const chartCompare = _chartCompare;
import _chartDo from './chart-do.svg';
export const chartDo = _chartDo;
import _chartFunction from './chart-function.svg';
export const chartFunction = _chartFunction;
import _chartLine from './chart-line.svg';
export const chartLine = _chartLine;
import _chartSave from './chart-save.svg';
export const chartSave = _chartSave;
import _chartUndo from './chart-undo.svg';
export const chartUndo = _chartUndo;
import _chart from './chart.svg';
export const chart = _chart;
import _chat from './chat.svg';
export const chat = _chat;
import _check from './check.svg';
export const check = _check;
import _circleMinus from './circle-minus.svg';
export const circleMinus = _circleMinus;
import _circlePlus from './circle-plus.svg';
export const circlePlus = _circlePlus;
import _clock from './clock.svg';
export const clock = _clock;
import _closeCircle from './close-circle.svg';
export const closeCircle = _closeCircle;
import _close from './close.svg';
export const close = _close;
import _cloudUpload from './cloud-upload.svg';
export const cloudUpload = _cloudUpload;
import _comment from './comment.svg';
export const comment = _comment;
import _company from './company.svg';
export const company = _company;
import _compareProposals from './compare-proposals.svg';
export const compareProposals = _compareProposals;
import _copy from './copy.svg';
export const copy = _copy;
import _creditCardBack from './credit-card-back.svg';
export const creditCardBack = _creditCardBack;
import _crosshair from './crosshair.svg';
export const crosshair = _crosshair;
import _cursos from './cursos.svg';
export const cursos = _cursos;
import _dashBtg from './dash-BTG.svg';
export const dashBtg = _dashBtg;
import _dashboard from './dashboard.svg';
export const dashboard = _dashboard;
import _diretorio from './diretorio.svg';
export const diretorio = _diretorio;
import _download from './download.svg';
export const download = _download;
import _drawArrow from './draw-arrow.svg';
export const drawArrow = _drawArrow;
import _drawCircle from './draw-circle.svg';
export const drawCircle = _drawCircle;
import _drawFibonacciArc from './draw-fibonacci-arc.svg';
export const drawFibonacciArc = _drawFibonacciArc;
import _drawFibonacciFan from './draw-fibonacci-fan.svg';
export const drawFibonacciFan = _drawFibonacciFan;
import _drawFibonacciRetracement from './draw-fibonacci-retracement.svg';
export const drawFibonacciRetracement = _drawFibonacciRetracement;
import _drawFibonacciTimezone from './draw-fibonacci-timezone.svg';
export const drawFibonacciTimezone = _drawFibonacciTimezone;
import _drawHorizontalArrow from './draw-horizontal-arrow.svg';
export const drawHorizontalArrow = _drawHorizontalArrow;
import _drawHorizontalLine from './draw-horizontal-line.svg';
export const drawHorizontalLine = _drawHorizontalLine;
import _drawHorizontalRange from './draw-horizontal-range.svg';
export const drawHorizontalRange = _drawHorizontalRange;
import _drawHorizontalRay from './draw-horizontal-ray.svg';
export const drawHorizontalRay = _drawHorizontalRay;
import _drawInfinity from './draw-infinity.svg';
export const drawInfinity = _drawInfinity;
import _drawMarker from './draw-marker.svg';
export const drawMarker = _drawMarker;
import _drawPitchfork from './draw-pitchfork.svg';
export const drawPitchfork = _drawPitchfork;
import _drawRay from './draw-ray.svg';
export const drawRay = _drawRay;
import _drawRetangle from './draw-retangle.svg';
export const drawRetangle = _drawRetangle;
import _drawText from './draw-text.svg';
export const drawText = _drawText;
import _drawTrendChannel from './draw-trend-channel.svg';
export const drawTrendChannel = _drawTrendChannel;
import _drawTrendLine from './draw-trend-line.svg';
export const drawTrendLine = _drawTrendLine;
import _drawTriangle from './draw-triangle.svg';
export const drawTriangle = _drawTriangle;
import _drawVerticalLine from './draw-vertical-line.svg';
export const drawVerticalLine = _drawVerticalLine;
import _drawVerticalRange from './draw-vertical-range.svg';
export const drawVerticalRange = _drawVerticalRange;
import _drawnMarker from './drawn-marker.svg';
export const drawnMarker = _drawnMarker;
import _edit2 from './edit-2.svg';
export const edit2 = _edit2;
import _editAtSign from './edit-at-sign.svg';
export const editAtSign = _editAtSign;
import _editAttach from './edit-attach.svg';
export const editAttach = _editAttach;
import _editBold from './edit-bold.svg';
export const editBold = _editBold;
import _editCenterAlign from './edit-center-align.svg';
export const editCenterAlign = _editCenterAlign;
import _editImage from './edit-image.svg';
export const editImage = _editImage;
import _editIndentLeft from './edit-indent-left.svg';
export const editIndentLeft = _editIndentLeft;
import _editIndentRight from './edit-indent-right.svg';
export const editIndentRight = _editIndentRight;
import _editItalic from './edit-italic.svg';
export const editItalic = _editItalic;
import _editLeftAlign from './edit-left-align.svg';
export const editLeftAlign = _editLeftAlign;
import _editLink from './edit-link.svg';
export const editLink = _editLink;
import _editNumberList from './edit-number-list.svg';
export const editNumberList = _editNumberList;
import _editPointList from './edit-point-list.svg';
export const editPointList = _editPointList;
import _editQuoteMark from './edit-quote-mark.svg';
export const editQuoteMark = _editQuoteMark;
import _editRightAlign from './edit-right-align.svg';
export const editRightAlign = _editRightAlign;
import _editStrikethrough from './edit-strikethrough.svg';
export const editStrikethrough = _editStrikethrough;
import _editUnderline from './edit-underline.svg';
export const editUnderline = _editUnderline;
import _edit from './edit.svg';
export const edit = _edit;
import _emojiAdd from './emoji-add.svg';
export const emojiAdd = _emojiAdd;
import _emojiSad from './emoji-sad.svg';
export const emojiSad = _emojiSad;
import _equity from './equity.svg';
export const equity = _equity;
import _fileDoc from './file-doc.svg';
export const fileDoc = _fileDoc;
import _fileEmpty from './file-empty.svg';
export const fileEmpty = _fileEmpty;
import _fileMp3 from './file-mp3.svg';
export const fileMp3 = _fileMp3;
import _filePdf from './file-pdf.svg';
export const filePdf = _filePdf;
import _filePpt from './file-ppt.svg';
export const filePpt = _filePpt;
import _fileText from './file-text.svg';
export const fileText = _fileText;
import _fileXls from './file-xls.svg';
export const fileXls = _fileXls;
import _fileXml from './file-xml.svg';
export const fileXml = _fileXml;
import _filter from './filter.svg';
export const filter = _filter;
import _folderFill from './folder-fill.svg';
export const folderFill = _folderFill;
import _folder from './folder.svg';
export const folder = _folder;
import _gavel from './gavel.svg';
export const gavel = _gavel;
import _gift from './gift.svg';
export const gift = _gift;
import _gripHorizontalLine from './grip-horizontal-line.svg';
export const gripHorizontalLine = _gripHorizontalLine;
import _gripHorizontalPoint from './grip-horizontal-point.svg';
export const gripHorizontalPoint = _gripHorizontalPoint;
import _gripVerticalLine from './grip-vertical-line.svg';
export const gripVerticalLine = _gripVerticalLine;
import _gripVerticalPoint from './grip-vertical-point.svg';
export const gripVerticalPoint = _gripVerticalPoint;
import _headphone from './headphone.svg';
export const headphone = _headphone;
import _headphones from './headphones.svg';
export const headphones = _headphones;
import _help from './help.svg';
export const help = _help;
import _hide from './hide.svg';
export const hide = _hide;
import _home from './home.svg';
export const home = _home;
import _hourGlass from './hour-glass.svg';
export const hourGlass = _hourGlass;
import _ideasEmptyStateFollowing from './ideas-empty-state-following.svg';
export const ideasEmptyStateFollowing = _ideasEmptyStateFollowing;
import _ideasEmptyStateMasterRequired from './ideas-empty-state-master-required.svg';
export const ideasEmptyStateMasterRequired = _ideasEmptyStateMasterRequired;
import _imageFill from './image-fill.svg';
export const imageFill = _imageFill;
import _indicator from './indicator.svg';
export const indicator = _indicator;
import _influencers from './influencers.svg';
export const influencers = _influencers;
import _infoCircleFill from './info-circle-fill.svg';
export const infoCircleFill = _infoCircleFill;
import _infoCircle from './info-circle.svg';
export const infoCircle = _infoCircle;
import _list from './list.svg';
export const list = _list;
import _live from './live.svg';
export const live = _live;
import _loadingDefault from './loading-default.svg';
export const loadingDefault = _loadingDefault;
import _lock from './lock.svg';
export const lock = _lock;
import _locked from './locked.svg';
export const locked = _locked;
import _logOut from './log-out.svg';
export const logOut = _logOut;
import _logoBubblesDark from './logo-bubbles-dark.svg';
export const logoBubblesDark = _logoBubblesDark;
import _logoBubblesLight from './logo-bubbles-light.svg';
export const logoBubblesLight = _logoBubblesLight;
import _logo from './logo.svg';
export const logo = _logo;
import _master from './master.svg';
export const master = _master;
import _matrix from './matrix.svg';
export const matrix = _matrix;
import _maximize from './maximize.svg';
export const maximize = _maximize;
import _megaphone from './megaphone.svg';
export const megaphone = _megaphone;
import _menu from './menu.svg';
export const menu = _menu;
import _minimize from './minimize.svg';
export const minimize = _minimize;
import _moneyBagFill from './money-bag-fill.svg';
export const moneyBagFill = _moneyBagFill;
import _moneyBag from './money-bag.svg';
export const moneyBag = _moneyBag;
import _moneyCoin from './money-coin.svg';
export const moneyCoin = _moneyCoin;
import _moneySign from './money-sign.svg';
export const moneySign = _moneySign;
import _moreOptionsHorizontal from './more-options-horizontal.svg';
export const moreOptionsHorizontal = _moreOptionsHorizontal;
import _moreOptionsVertical from './more-options-vertical.svg';
export const moreOptionsVertical = _moreOptionsVertical;
import _move from './move.svg';
export const move = _move;
import _mover from './mover.svg';
export const mover = _mover;
import _mute from './mute.svg';
export const mute = _mute;
import _next from './next.svg';
export const next = _next;
import _notificationFill from './notification-fill.svg';
export const notificationFill = _notificationFill;
import _notification from './notification.svg';
export const notification = _notification;
import _patchCheck from './patch-check.svg';
export const patchCheck = _patchCheck;
import _pauseCircle from './pause-circle.svg';
export const pauseCircle = _pauseCircle;
import _pause from './pause.svg';
export const pause = _pause;
import _paymentMastercard from './payment-mastercard.svg';
export const paymentMastercard = _paymentMastercard;
import _pen from './pen.svg';
export const pen = _pen;
import _percentage from './percentage.svg';
export const percentage = _percentage;
import _pin from './pin.svg';
export const pin = _pin;
import _plantao from './plantao.svg';
export const plantao = _plantao;
import _playCircle from './play-circle.svg';
export const playCircle = _playCircle;
import _playFill from './play-fill.svg';
export const playFill = _playFill;
import _playStore from './play-store.svg';
export const playStore = _playStore;
import _play from './play.svg';
export const play = _play;
import _plus from './plus.svg';
export const plus = _plus;
import _previus from './previus.svg';
export const previus = _previus;
import _proposalDetails from './proposal-details.svg';
export const proposalDetails = _proposalDetails;
import _radioMic from './radio-mic.svg';
export const radioMic = _radioMic;
import _radio from './radio.svg';
export const radio = _radio;
import _ranking from './ranking.svg';
export const ranking = _ranking;
import _refreshSlash from './refresh-slash.svg';
export const refreshSlash = _refreshSlash;
import _refresh from './refresh.svg';
export const refresh = _refresh;
import _reports from './reports.svg';
export const reports = _reports;
import _revert from './revert.svg';
export const revert = _revert;
import _rotate from './rotate.svg';
export const rotate = _rotate;
import _search from './search.svg';
export const search = _search;
import _selectorBigger from './selector-bigger.svg';
export const selectorBigger = _selectorBigger;
import _selectorDefault from './selector-default.svg';
export const selectorDefault = _selectorDefault;
import _selectorSmaller from './selector-smaller.svg';
export const selectorSmaller = _selectorSmaller;
import _selector from './selector.svg';
export const selector = _selector;
import _sell from './sell.svg';
export const sell = _sell;
import _send from './send.svg';
export const send = _send;
import _settings from './settings.svg';
export const settings = _settings;
import _share from './share.svg';
export const share = _share;
import _shieldCheck from './shield-check.svg';
export const shieldCheck = _shieldCheck;
import _shield from './shield.svg';
export const shield = _shield;
import _show from './show.svg';
export const show = _show;
import _slidersVertical from './sliders-vertical.svg';
export const slidersVertical = _slidersVertical;
import _sliders from './sliders.svg';
export const sliders = _sliders;
import _soundOn from './sound-on.svg';
export const soundOn = _soundOn;
import _speakerphone from './speakerphone.svg';
export const speakerphone = _speakerphone;
import _starFill from './star-fill.svg';
export const starFill = _starFill;
import _star from './star.svg';
export const star = _star;
import _station from './station.svg';
export const station = _station;
import _store from './store.svg';
export const store = _store;
import _suitabilityTestDark from './suitability-test-dark.svg';
export const suitabilityTestDark = _suitabilityTestDark;
import _suitabilityTestResult from './suitability-test-result.svg';
export const suitabilityTestResult = _suitabilityTestResult;
import _suitabilityTest from './suitability-test.svg';
export const suitabilityTest = _suitabilityTest;
import _support from './support.svg';
export const support = _support;
import _tcMarkerDown from './tc-marker-down.svg';
export const tcMarkerDown = _tcMarkerDown;
import _tcOptions from './tc-options.svg';
export const tcOptions = _tcOptions;
import _thumbDown from './thumb-down.svg';
export const thumbDown = _thumbDown;
import _thumbUp from './thumb-up.svg';
export const thumbUp = _thumbUp;
import _timeEvent from './time-event.svg';
export const timeEvent = _timeEvent;
import _toggleOff from './toggle-off.svg';
export const toggleOff = _toggleOff;
import _toggleOn from './toggle-on.svg';
export const toggleOn = _toggleOn;
import _tools from './tools.svg';
export const tools = _tools;
import _torneio from './torneio.svg';
export const torneio = _torneio;
import _torneios from './torneios.svg';
export const torneios = _torneios;
import _tradeIdeas from './trade-ideas.svg';
export const tradeIdeas = _tradeIdeas;
import _trash from './trash.svg';
export const trash = _trash;
import _upload from './upload.svg';
export const upload = _upload;
import _userAdd from './user-add.svg';
export const userAdd = _userAdd;
import _userList from './user-list.svg';
export const userList = _userList;
import _user from './user.svg';
export const user = _user;
import _users from './users.svg';
export const users = _users;
import _video from './video.svg';
export const video = _video;
import _voucher from './voucher.svg';
export const voucher = _voucher;
import _wealth from './wealth.svg';
export const wealth = _wealth;
