import _area from './Area.svg';
import _arrow from './Arrow.svg';
import _bars from './Bars.svg';
import _camera from './Camera.svg';
import _candles from './Candles.svg';
export const area = _area;
export const arrow = _arrow;
export const bars = _bars;
export const camera = _camera;
export const candles = _candles;
